### ISSUE TITLE
Add shi7en src. Include shi7en binaries in release.

### ISSUE THREAD

**Issue by bhillmann** [knights-lab/shi7#10]
This is the file that should go in the 'src' folder of the root of the project. https://github.com/GabeAl/NINJA-SHI7/blob/master/ninja_shi7.c

Should be renamed to 'shi7en_trimmer'.

**Comment by GabeAl** [comment]
I put in the source -- binaries should also be in the release (but check the names!)

**Comment by bhillmann** [comment]
@GabeAl Can we get the commands you ran to compile the static binaries so that we can build a Makefile? The Python source code needs to be in sync with what we call the binaries.

**Comment by GabeAl** [comment]
Sure, we can get one for us to test. I'll add it.

Quick note just in case: we can't really depend on anyone besides us using it -- it will not be the same for clang or windows, or some versions of gcc on Linux, so it's practically useless for anyone but us 👍

**Comment by bhillmann** [comment]
We can specify what version of clang/gcc they need.

**Comment by GabeAl** [comment]
Doesn't mean they can feasibly -- or even reasonably -- get it working. :) But yes, we can and should say what could be used to compile everything. 

It's also different depending on Windows/Linux/Mac. It's also different depending on what GCC _distribution_ (not version) they're using (Mac's homebrew GCC is broken with binutils and can't handle AVX; hpc-osx can't handle LTO, Clang can't handle OpenMP or nested functions or some intrinsics, etc -- this has nothing to do with GCC version, but the quirks of the distribution of the same version of GCC). And some linux systems might not support static compilation because they don't have static binutils, or a static glibc to link in -- this is a big dependency chain. Windows has myriad flavors of GCC too, and users in the new Windows 10 bash would have a different set of options [they use the linux ones] vs mingw gcc vs cygwin... and these often don't work outside the terminal environments they're made for, so the resulting binaries won't work outside of the terminal that compiled them, making the self-compiled stuff non-interoperable with others.

So again -- yes, but we should never depend on it!

**Comment by GabeAl** [comment]
gcc 5,6,7: 
gcc -m64 -Ofast -fwhole-program -flto -march=nehalem -static -fopenmp
should cover the bases actually. Literally. Base coverage. QC. Heh. Heh...

Need a list of what binaries are needed and what to name them! I'm going to go off the install script for now.

**Comment by bhillmann** [comment]
This is done.
