### ISSUE TITLE
CRITICAL: Paired ends are NOT correctly paired

### ISSUE THREAD

**Issue by GabeAl** [knights-lab/shi7#27]
Seeing the files not paired correctly:
```
12/16/2016 10:14:53 AM Debug Mode is Enabled. Retaining intermediate files.
12/16/2016 10:14:53 AM ['raw/CZ-MB4_S4_L001_R2_001.fastq', 'raw/CZ-MB124_S124_L001_R1_001.fastq', 'raw/CZ-MB19_S19_L001_R2_001.fastq', 'raw/CZ-MB24_S24_L001_R2_001.fastq', 'raw/CZ-MB87_S87_L001_R2_001.fastq', 'raw/CZ-MB124_S124_L001_R2_001.fastq', 'raw/CZ-MB114_S114_L001_R1_001.fastq', 'raw/CZ-MB101_S101_L001_R2_001.fastq', 'raw/CZ-MB32_S32_L001_R2_001.fastq', 'raw/CZ-MB108_S108_L001_R1_001.fastq', 'raw/CZ-MB121_S121_L001_R2_001.fastq', 'raw/CZ-MB128_S128_L001_R2_001.fastq', 'raw/CZ-MB75_S75_L001_R2_001.fastq',

etc.

```
The reads are not actually paired correctly, causing everything in PE processing to fail. This is a critical flaw and needs to be patched ASAP. 

[edit] Seems to be working now, but awaiting confirmation (reply to this thread)

**Comment by GabeAl** [comment]
@bhillmann 
Any idea why this is still happening? Is this a version problem again? I though the new version didn't spit out this list of file names?

Anything we can do to help debug on our end? My python knowledge is limited, but I would imagine it's just some quirk having to do with how these are sorted. Any chance of replacing with a regular expression like in the old shell script?

Thanks!

**Comment by bhillmann** [comment]
Update is pushed. I'm not sure if you have the most recent version. If we get to a stable version, we should start making releases so that we can verify what version people have. 

And yes, you can use a regular expression, but we need to be careful if R1,R2 appear in the filename itself.

I now sort and then split on even odd index. Since we have a list of filenames sorted alphabetically this should work.,

**Comment by GabeAl** [comment]
Sounds good. Another suggestion would be to write the version to the log
with every run. I wonder if there's a way github can automatically assign a
version string based on commit (just the first few digits of the hash or
something).

Thanks!

**Comment by GabeAl** [comment]
This seems to work now, even if it appears a bit "ad hoc." 

The pros of this method are: doesn't need specific pattern to identify R1 and R2 reads. 
The cons of this method are: can't use a specific pattern to verify R1 and R2 reads. 

A combination would be to look for the "last changed number" and make sure it goes from "1" (in the R1s) to "2" (in the R2s). 
Example: 
My read1 filename is: TKJMC_FMK01.1.001.fastq
My read2 filename is: TKJMC_FMK01.2.001.fastq

The current way would work, but hunting for "R1" would not, nor would looking for the last "1" or whatever. The _last changed number_ might be a good proxy but for now I think it's fine to leave it be. Any thoughts on this?

**Comment by bhillmann** [comment]
Philosophically, I think this is a deeper issue with sequencing data. Although working with large flat files is easy intuitively, I think having data machine readable and code human readable would put this discussion in its Kafan before it happened. Having a replacement specification for FASTQs should be a higher priority.

Anyway, I don't know of a good REGEX that could fix our problem, as you stated due to the discrepancies of naming conventions with "1/2" and "R1/R2". What do you think of the user making an R1/R2 mapping file? Or aligning the filenames and looking for only a single mismatch?

**Comment by GabeAl** [comment]
Might be good in the long-term, but as long as the docs are clear that the set of forwards and reverse fastqs should be there, the goal is to make things for them and us simple. The fewer hurdles to leap the better. I'll close this for the time being!
