### ISSUE TITLE
Speed up the python parse/write (Convert/combine fasta steps)

### ISSUE THREAD

**Issue by GabeAl** [knights-lab/shi7#36]
It seems for the test HMP samples on multi-core systems (16 threads) the trimmomatic and flash steps run in less than 5 minutes but the python script that converts and/or writes to QIIME formatted FASTA takes another 10. Is there some way to speed this up (yield?).

**Comment by bhillmann** [comment]
Yes, there are a couple of optimizations that wouldn't take very long.

1. Currently runs single-threaded
2. FASTQ parser needs testing setup for optimization (currently does do yield, just need readily available testing for it)
3. Parse binary file objects instead of Python strings ('bw' instead of 'w')

**Comment by GabeAl** [comment]
I like #3. Almost seems too easy... :)

**Comment by bhillmann** [comment]
3 Failed, it appeared to be slower. FASTQ parser has been updated, and new loop may yield faster processing. Should run them in parallel in the convert. The combine cannot be.
