### ISSUE TITLE
Switch the 'no' flags to boolean flags

### ISSUE THREAD

**Issue by bhillmann** [knights-lab/shi7#9]
The flags 
```
--no_<more>
```

Should be set to be:

```
--<more> {True/False}
```

To  avoid confusion.

Also the user should not be able to make a 'combined FASTQ'. Explicitly fail at arg checking if this is the case and tell the user to change their arguments.

**Comment by kaiweiang** [comment]
If we want the format `--<more> {True/False}` , that means user will be passing True/False in string and the program will run into a similar problem with [this](http://stackoverflow.com/questions/15008758/parsing-boolean-values-with-argparse), since `action=store_true/false` is not applicable here (I think). So, do we need to convert the string to boolean variable manually as the post suggested? Or is there any better way that I don't know about?

**Comment by bhillmann** [comment]
We need to explicitly pass True or False with the flags. This will forego the ```action=store_true/false``` command unfortunately. This is backtracking for usability, rather than code efficiency.
